### ISSUE TITLE
the node doesn´t resize after adding new inputs

### ISSUE THREAD

**Issue by KoreTeknology** [cozy-comfyui/cozy_ex_dynamic#2]
the node widget doesnt resize in height when adding new inputs

**Comment by Amorano** [comment]
I will see about adding a resize function too -- its just not something that comes in the ComfyUI and we each have to make it ourselves atm. Most likely will rip it from Jovimetrix.

**Comment by Amorano** [comment]
> the node widget doesnt resize in height when adding new inputs

I took a look, and the default behavior does collapse and expand. Are you perhaps not on the latest frontend? I use @latest and not the version locked on that ships with whatever version of ComfyUI is out.

![image](https://github.com/user-attachments/assets/523443bd-3022-4563-a905-eec7fc866b3b)


https://github.com/user-attachments/assets/8ac4b7e6-6c89-49bd-9d23-20a343c8fcd2



Let me know if that is not what you are seeing? Perhaps it is a browser problem? I am using Firefox.
